//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PasswordGenerationFormsClient.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VowelCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpperCaseCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReverseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::PasswordGenerationFormsClient.Properties.Settings.Default.PasswordGenerationFormsClient_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VowelCountCompletedEventHandler VowelCountCompleted;
        
        /// <remarks/>
        public event UpperCaseCountCompletedEventHandler UpperCaseCountCompleted;
        
        /// <remarks/>
        public event ReverseCompletedEventHandler ReverseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/VowelCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void VowelCount([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string word, out int VowelCountResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool VowelCountResultSpecified) {
            object[] results = this.Invoke("VowelCount", new object[] {
                        word});
            VowelCountResult = ((int)(results[0]));
            VowelCountResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void VowelCountAsync(string word) {
            this.VowelCountAsync(word, null);
        }
        
        /// <remarks/>
        public void VowelCountAsync(string word, object userState) {
            if ((this.VowelCountOperationCompleted == null)) {
                this.VowelCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVowelCountOperationCompleted);
            }
            this.InvokeAsync("VowelCount", new object[] {
                        word}, this.VowelCountOperationCompleted, userState);
        }
        
        private void OnVowelCountOperationCompleted(object arg) {
            if ((this.VowelCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VowelCountCompleted(this, new VowelCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/UpperCaseCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpperCaseCount([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string word, out int UpperCaseCountResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool UpperCaseCountResultSpecified) {
            object[] results = this.Invoke("UpperCaseCount", new object[] {
                        word});
            UpperCaseCountResult = ((int)(results[0]));
            UpperCaseCountResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void UpperCaseCountAsync(string word) {
            this.UpperCaseCountAsync(word, null);
        }
        
        /// <remarks/>
        public void UpperCaseCountAsync(string word, object userState) {
            if ((this.UpperCaseCountOperationCompleted == null)) {
                this.UpperCaseCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpperCaseCountOperationCompleted);
            }
            this.InvokeAsync("UpperCaseCount", new object[] {
                        word}, this.UpperCaseCountOperationCompleted, userState);
        }
        
        private void OnUpperCaseCountOperationCompleted(object arg) {
            if ((this.UpperCaseCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpperCaseCountCompleted(this, new UpperCaseCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Reverse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reverse([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string word) {
            object[] results = this.Invoke("Reverse", new object[] {
                        word});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReverseAsync(string word) {
            this.ReverseAsync(word, null);
        }
        
        /// <remarks/>
        public void ReverseAsync(string word, object userState) {
            if ((this.ReverseOperationCompleted == null)) {
                this.ReverseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReverseOperationCompleted);
            }
            this.InvokeAsync("Reverse", new object[] {
                        word}, this.ReverseOperationCompleted, userState);
        }
        
        private void OnReverseOperationCompleted(object arg) {
            if ((this.ReverseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReverseCompleted(this, new ReverseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void VowelCountCompletedEventHandler(object sender, VowelCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VowelCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VowelCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int VowelCountResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool VowelCountResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpperCaseCountCompletedEventHandler(object sender, UpperCaseCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpperCaseCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpperCaseCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int UpperCaseCountResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool UpperCaseCountResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ReverseCompletedEventHandler(object sender, ReverseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReverseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReverseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591