//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordGenerationFormsWebClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VowelCount", ReplyAction="http://tempuri.org/IService1/VowelCountResponse")]
        int VowelCount(string word);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VowelCount", ReplyAction="http://tempuri.org/IService1/VowelCountResponse")]
        System.Threading.Tasks.Task<int> VowelCountAsync(string word);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpperCaseCount", ReplyAction="http://tempuri.org/IService1/UpperCaseCountResponse")]
        int UpperCaseCount(string word);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpperCaseCount", ReplyAction="http://tempuri.org/IService1/UpperCaseCountResponse")]
        System.Threading.Tasks.Task<int> UpperCaseCountAsync(string word);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Reverse", ReplyAction="http://tempuri.org/IService1/ReverseResponse")]
        string Reverse(string word);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Reverse", ReplyAction="http://tempuri.org/IService1/ReverseResponse")]
        System.Threading.Tasks.Task<string> ReverseAsync(string word);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PasswordGenerationFormsWebClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PasswordGenerationFormsWebClient.ServiceReference1.IService1>, PasswordGenerationFormsWebClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int VowelCount(string word) {
            return base.Channel.VowelCount(word);
        }
        
        public System.Threading.Tasks.Task<int> VowelCountAsync(string word) {
            return base.Channel.VowelCountAsync(word);
        }
        
        public int UpperCaseCount(string word) {
            return base.Channel.UpperCaseCount(word);
        }
        
        public System.Threading.Tasks.Task<int> UpperCaseCountAsync(string word) {
            return base.Channel.UpperCaseCountAsync(word);
        }
        
        public string Reverse(string word) {
            return base.Channel.Reverse(word);
        }
        
        public System.Threading.Tasks.Task<string> ReverseAsync(string word) {
            return base.Channel.ReverseAsync(word);
        }
    }
}
